---
- name: "Ensure the jenkins apt repository key is installed in Ubuntu servers"
  apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present
  become: true

- name: "Ensure the repository is configured in Ubuntu Servers"
  apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present
  become: true

- name: "Ensure jenkins is installed in Ubuntu servers"
  apt: name=jenkins update_cache=yes state=present
  become: true
  notify:
     - start jenkins
